# Generated by Django 5.2.17 on 2026-09-29 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(default='RECEIVED', max_length=50)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='work_items__status_00c8a5_idx'), models.Index(fields=['external_id'], name='work_items__externa_d018c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='work_items.workitem')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
    ]
